### PR TITLE
Default to allow capital letters in usernames

### PR DESCRIPTION
**Pull request by myoung34**
LDAP `sAMAccountName` name is case insensitive (or rather should be)

### CODE REVIEW

**Comment by dhirschfeld** [comment]
It's a configurable - you can choose whatever regex you want:
```python
c.LDAPAuthenticator.valid_username_regex =  r'^[a-zA-Z][.a-zA-Z0-9_-]*$'
```

**Comment by consideRatio** [comment]
@dhirschfeld what do you think about this default value and merging this PR?

The key consideration I have, is regarding if you may end up with the same user having two different JupyterHub identities because the user signed in as Erik rather than erik once or similar, that would be problematic.

**Comment by dhirschfeld** [comment]
I have similar concerns and whilst I'd be happy to change the default the internal representation should probably be lowercased to avoid duplicates. I'd need to actually review the code to see if that is an actual problem which should be properly handled.

**Comment by manics** [comment]
Maybe the author @myoung34 can help- can you tell us a bit more about your use-case? Did you run into problems when you allowed mixed case usernames using the configurable?

**Comment by myoung34** [comment]
I ran into this problem a long time ago, yes. The use-case still exists but I'm no longer at that company or codebase.

Fact is on linux with this `sAMAccountName` == 'mYoung' or similar (human inputted) would fail

**Comment by manics** [comment]
@myoung34 Should ldapauthenticator accept any case but always lower case the username before passing it to JupyterHub, or are there situations where the case should be maintained i.e. where `erik` and `Erik` really are two separate users?

**Comment by myoung34** [comment]
AD wont allow those to be different users so its safe for the CLI/implementation end to allow it IMO

**Comment by manics** [comment]
I'm going to close this since there's no consensus on this change, and there's a current workaround.

**Pull request closed without merging**
