### PR TITLE
Added new config params for using NTLM based authentication ( ie: windows ldap server)

### PR DESCRIPTION
**Pull request by oneklc**
Was easy to modify to add NTLM support. 
I did not test previous settings to see if they still work.
The changes made are just working for me. 
Feel free to reject the pull request. 
Thanks for maintaining the ldapauthenticator.

### CODE REVIEW

**Comment by willingc** [comment]
Thanks for the PR @oneklc.

I'm going to defer to @yuvipanda for a formal review since Yuvi has been most involved in this authenticator. 

A few general thoughts:
- NTLM: Perhaps it makes more sense for the default to be set to False for NTLM and have those interested in this authentication to opt in
- setup.py: I don't believe that these changes are needed

**Comment by oneklc** [comment]
Agreed regarding NTLM defaulting to false and
setup.py changes are totally junkable.

**Comment by yuvipanda** [comment]
Hello!

I'm inclined to merge #12 first, since that seems to be required in some ways for proper AD support.

**Comment by yuvipanda** [comment]
Hello! I'm going to discard this for right now, since a bunch of other related PRs were merged. Feel free to re-open if they are missing some feature this needs! 

Thanks for the patch :)

**Pull request closed without merging**
