### PR TITLE
Exchanging ldap3 constants in if/else

### PR DESCRIPTION
**Pull request by 1kastner**
They were just the wrong way round and no error has popped up so far, see the ldap3 author's statements at https://github.com/cannatag/ldap3/issues/855

### CODE REVIEW

**Comment by 1kastner** [comment]
@manics I hope everything is solved. I believe use_ssl means either SSL or STARTTLS is used, right? Unencrypted communication is not supported at all, is it?

**Comment by 1kastner** [comment]
PS: For me the solution is working in application and the tests pass, I don't know how many more test cases are needed here.

**Review by manics — APPROVED** [review]
Thanks for fixing this! The fix makes sense to me

@dhirschfeld would you mind giving a 👍 since you're more familiar with the code? Thanks!

**Review by dhirschfeld — APPROVED** [review]
LGTM

**Comment by dhirschfeld** [comment]
I haven't looked at this code in a long time but the description in the linked issue seems pretty clear.

:shipit:

**Comment by manics** [comment]
I've just tagged 1.3.2 so it should be on pypi soon.

In general conda-forge packages are maintained independently of the Python/Pypi package: https://github.com/conda-forge/jupyterhub-ldapauthenticator-feedstock

Though in this case [some of the maintainers overlap](https://github.com/conda-forge/jupyterhub-ldapauthenticator-feedstock/blob/e79cc5706f604575f59362dadd81fc9f8ffdf2ef/recipe/meta.yaml#L43-L45)

**Comment by 1kastner** [comment]
@manics so the github releases (see https://github.com/jupyterhub/ldapauthenticator/releases ) are not used anymore?

**Comment by dhirschfeld** [comment]
GitHub "releases" are just some UI sugar on top of an ordinary git tag and don't add anything *required* for packaging. By default `conda-forge` builds from the pypi sources.

All the tags can be seen in the tags view: https://github.com/jupyterhub/ldapauthenticator/tags

**Comment by 1kastner** [comment]
Thank you very much for that information!

**Pull request merged**
